/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlysinhviendemo.ui;

import com.google.gson.Gson;
import com.mycompany.quanlysinhviendemo.model.SinhVien;
import com.mycompany.quanlysinhviendemo.service.impl.HocBongLoaiKha;
import static com.mycompany.quanlysinhviendemo.ui.QuanLy.data;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANGPHUC
 */
public class HocBongKha extends javax.swing.JPanel {

    public static int sttKha = 1;
    DefaultTableModel modelKha;
    List<SinhVien> listKha = new ArrayList<>();

    /**
     * Creates new form HocBongKha
     */
    public HocBongKha() {
        initComponents();
        modelKha = (DefaultTableModel) tblKha.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKha = new javax.swing.JTable();
        btnCapNhatKha = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(770, 580));
        setPreferredSize(new java.awt.Dimension(770, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách sinh viên đạt học bổng loại Khá");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        tblKha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ và tên", "Mã SV", "Lớp", "Ngày sinh", "Quê quán", "Khoa", "Điểm TB"
            }
        ));
        jScrollPane1.setViewportView(tblKha);
        if (tblKha.getColumnModel().getColumnCount() > 0) {
            tblKha.getColumnModel().getColumn(0).setMinWidth(45);
            tblKha.getColumnModel().getColumn(0).setMaxWidth(50);
            tblKha.getColumnModel().getColumn(1).setMinWidth(200);
            tblKha.getColumnModel().getColumn(1).setMaxWidth(210);
            tblKha.getColumnModel().getColumn(3).setMinWidth(55);
            tblKha.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 760, -1));

        btnCapNhatKha.setText("Cập nhật");
        btnCapNhatKha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatKhaActionPerformed(evt);
            }
        });
        add(btnCapNhatKha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatKhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatKhaActionPerformed

        if(modelKha.getRowCount()==0){
            fillToTableKha();
        }else{
            for(int i = modelKha.getRowCount()-1;i>=0;i--){
                modelKha.removeRow(i);
            }
            sttKha = 1;
            fillToTableKha();
        }
    }//GEN-LAST:event_btnCapNhatKhaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save a file");

        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.json", "json"));

        int value = fileChooser.showSaveDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            FileWriter fw = null;
            try {
                fw = new FileWriter(file);

                Gson gson = new Gson();
                gson.toJson(listKha, fw);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (fw != null) {
                    try {
                        fw.flush();
                        fw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed
    public void fillToTableKha() {
        HocBongLoaiKha kha = new HocBongLoaiKha();
        listKha = kha.HocBongKha(QuanLy.data);
        if (listKha != null) {
            for (int i = 0; i < listKha.size(); i++) {
                SinhVien sv = listKha.get(i);
                modelKha.addRow(new Object[]{
                    sttKha++,
                    sv.getHoTen(),
                    sv.getMaSV(),
                    sv.getLopNienChe(),
                    sv.getNgaySinh().toString(),
                    sv.getQueQuan(),
                    sv.shortName,
                    String.valueOf(sv.tinhDiem())
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatKha;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKha;
    // End of variables declaration//GEN-END:variables
}
