/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlysinhviendemo.ui;

import com.google.gson.Gson;
import com.mycompany.quanlysinhviendemo.model.SinhVien;
import com.mycompany.quanlysinhviendemo.service.impl.HocBongLoaiGioi;
import static com.mycompany.quanlysinhviendemo.ui.QuanLy.data;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANGPHUC
 */
public class HocBongGioi extends javax.swing.JPanel {
    
    public static int sttGioi = 1;
    DefaultTableModel modelGioi;
    public List<SinhVien> listGioi = new ArrayList<>(); 

    /**
     * Creates new form HocBongGioi
     */
    public HocBongGioi() {
        initComponents();
        modelGioi = (DefaultTableModel) tblGioi.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioi = new javax.swing.JTable();
        btnCapNhatGioi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(770, 580));
        setPreferredSize(new java.awt.Dimension(770, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách sinh viên đạt học bổng Giỏi");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 30));

        tblGioi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ và tên", "Mã SV", "Lớp", "Ngày sinh", "Quê quán", "Khoa", "Điểm TB"
            }
        ));
        jScrollPane1.setViewportView(tblGioi);
        if (tblGioi.getColumnModel().getColumnCount() > 0) {
            tblGioi.getColumnModel().getColumn(0).setMinWidth(45);
            tblGioi.getColumnModel().getColumn(0).setMaxWidth(50);
            tblGioi.getColumnModel().getColumn(1).setMinWidth(200);
            tblGioi.getColumnModel().getColumn(1).setMaxWidth(210);
            tblGioi.getColumnModel().getColumn(3).setMinWidth(55);
            tblGioi.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 750, -1));

        btnCapNhatGioi.setText("Cập nhật");
        btnCapNhatGioi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatGioiActionPerformed(evt);
            }
        });
        add(btnCapNhatGioi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatGioiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatGioiActionPerformed
        if(modelGioi.getRowCount()==0){
            fillToTableGioi();
        }else{
            for(int i = modelGioi.getRowCount()-1;i>=0;i--){
                modelGioi.removeRow(i);
            }
            sttGioi = 1;
            fillToTableGioi();
        }
    }//GEN-LAST:event_btnCapNhatGioiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save a file");

        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.json", "json"));

        int value = fileChooser.showSaveDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            FileWriter fw = null;
            try {
                fw = new FileWriter(file);

                Gson gson = new Gson();
                gson.toJson(listGioi, fw);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (fw != null) {
                    try {
                        fw.flush();
                        fw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed
    public void fillToTableGioi() {
        HocBongLoaiGioi gioi = new HocBongLoaiGioi();
        listGioi = gioi.HocBongGioi(QuanLy.data);
        if (listGioi != null) {
            for (int i = 0; i < listGioi.size(); i++) {
                SinhVien sv = listGioi.get(i);
                modelGioi.addRow(new Object[]{
                    sttGioi++,
                    sv.getHoTen(),
                    sv.getMaSV(),
                    sv.getLopNienChe(),
                    sv.getNgaySinh().toString(),
                    sv.getQueQuan(),
                    sv.shortName,
                    String.valueOf(sv.tinhDiem())
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatGioi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGioi;
    // End of variables declaration//GEN-END:variables
}
