/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlysinhviendemo.ui;

import com.mycompany.quanlysinhviendemo.model.SinhVien;
import static com.mycompany.quanlysinhviendemo.ui.QuanLy.data;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANGPHUC
 */
public class locLopNienChe extends javax.swing.JPanel {

    private static List<SinhVien> listHocSinh;
    DefaultTableModel modelLocLop;
    public static int stt = 1;

    /**
     * Creates new form locLopNienChe
     */
    public locLopNienChe() {
        initComponents();
        modelLocLop = (DefaultTableModel) tblLocLop.getModel();
    }

    public void fillToTableLocLop() {
        listHocSinh = new ArrayList<>();
        for (SinhVien s : data) {
            if (s.getLopNienChe().equals(txttenLop.getText())) {
                listHocSinh.add(s);
            }
        }
        if (listHocSinh != null) {
            for (int i = 0; i < listHocSinh.size(); i++) {
                SinhVien sv = listHocSinh.get(i);
                modelLocLop.addRow(new Object[]{
                    stt++,
                    sv.getHoTen(),
                    sv.getMaSV(),
                    sv.getLopNienChe(),
                    sv.getNgaySinh(),
                    sv.getQueQuan(),
                    sv.shortName,
                    String.valueOf(sv.tinhDiem())
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttenLop = new javax.swing.JTextField();
        btnLocLop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocLop = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(770, 580));
        setPreferredSize(new java.awt.Dimension(770, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Lọc sinh viên theo lớp niên chế");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));
        add(txttenLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 510, 40));

        btnLocLop.setText("Lọc");
        btnLocLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocLopActionPerformed(evt);
            }
        });
        add(btnLocLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        tblLocLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ và tên", "Mã SV", "Lớp", "Ngày sinh", "Quê quán", "Khoa", "Điểm TB"
            }
        ));
        jScrollPane1.setViewportView(tblLocLop);
        if (tblLocLop.getColumnModel().getColumnCount() > 0) {
            tblLocLop.getColumnModel().getColumn(0).setMinWidth(45);
            tblLocLop.getColumnModel().getColumn(0).setMaxWidth(50);
            tblLocLop.getColumnModel().getColumn(1).setMinWidth(200);
            tblLocLop.getColumnModel().getColumn(1).setMaxWidth(210);
            tblLocLop.getColumnModel().getColumn(3).setMinWidth(55);
            tblLocLop.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 750, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocLopActionPerformed
        // TODO add your handling code here:                                         
        // TODO add your handling code here:
        if (txttenLop.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Ban Chua Nhap Lop Can Tim Can Tim", "Canh Bao:", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (modelLocLop.getRowCount() == 0) {
            fillToTableLocLop();
            listHocSinh = null;
        } else {
            for (int i = modelLocLop.getRowCount() - 1; i >= 0; i--) {
                modelLocLop.removeRow(i);
            }
            stt = 1;
            fillToTableLocLop();
            if (listHocSinh.size() == 0) {
                JOptionPane.showMessageDialog(this, "Khong Co Lop Can Tim", "Canh Bao:", JOptionPane.ERROR_MESSAGE);
                return;
            }
            listHocSinh = null;
        }
    }//GEN-LAST:event_btnLocLopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLocLop;
    private javax.swing.JTextField txttenLop;
    // End of variables declaration//GEN-END:variables
}
