/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlysinhviendemo.ui;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.mycompany.quanlysinhviendemo.model.SinhVien;
import static com.mycompany.quanlysinhviendemo.ui.QuanLy.data;
import static com.mycompany.quanlysinhviendemo.ui.QuanLy.stt;
import static com.mycompany.quanlysinhviendemo.ui.TimKiemSinhVien.manHinh;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTabbedPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANGPHUC
 */
public class Main extends javax.swing.JFrame {

    public static QuanLy manageSV = new QuanLy();
    private HocBongKha hbKha;
    private HocBongGioi hbGioi;
    private DanhSachHocLai dsHL;
    private TimKiemSinhVien timKiem;
    DefaultTableModel model;
    locLopNienChe loc;
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        model = (DefaultTableModel) manageSV.getTblDanhSach().getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        tbpMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuiMoFile = new javax.swing.JMenuItem();
        mnuiLuuFile = new javax.swing.JMenuItem();
        mnuQL = new javax.swing.JMenu();
        mnuiQL = new javax.swing.JMenuItem();
        mnuiGioi = new javax.swing.JMenuItem();
        mnuiKha = new javax.swing.JMenuItem();
        mnuiHocLai = new javax.swing.JMenuItem();
        mnuCongCu = new javax.swing.JMenu();
        mnuiTimKiem = new javax.swing.JMenuItem();
        mnuiLoc = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuiMoFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiMoFile.setText("Mở File Json");
        mnuiMoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiMoFileActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiMoFile);

        mnuiLuuFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiLuuFile.setText("Lưu File Json");
        mnuiLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLuuFileActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiLuuFile);

        jMenuBar1.add(jMenu1);

        mnuQL.setText("Quản lý sinh viên");

        mnuiQL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiQL.setText("Danh sách");
        mnuiQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiQLActionPerformed(evt);
            }
        });
        mnuQL.add(mnuiQL);

        mnuiGioi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiGioi.setText("Học bổng loại Giỏi");
        mnuiGioi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiGioiActionPerformed(evt);
            }
        });
        mnuQL.add(mnuiGioi);

        mnuiKha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiKha.setText("Học bổng loại Khá");
        mnuiKha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiKhaActionPerformed(evt);
            }
        });
        mnuQL.add(mnuiKha);

        mnuiHocLai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiHocLai.setText("Danh sách học lại");
        mnuiHocLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiHocLaiActionPerformed(evt);
            }
        });
        mnuQL.add(mnuiHocLai);

        jMenuBar1.add(mnuQL);

        mnuCongCu.setText("Công cụ");

        mnuiTimKiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiTimKiem.setText("Tìm Kiếm");
        mnuiTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiTimKiemActionPerformed(evt);
            }
        });
        mnuCongCu.add(mnuiTimKiem);

        mnuiLoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiLoc.setText("Lọc");
        mnuiLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLocActionPerformed(evt);
            }
        });
        mnuCongCu.add(mnuiLoc);

        jMenuBar1.add(mnuCongCu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillToJTable() {
        if (data != null) {
            for (SinhVien s : data) {
                model.addRow(new Object[]{
                    stt++,
                    s.getHoTen(),
                    s.getMaSV(),
                    s.getLopNienChe(),
                    s.getNgaySinh(),
                    s.getQueQuan(),
                    s.shortName,
                    String.valueOf(s.tinhDiem())
                });
            }
        }
    }

    private void mnuiQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiQLActionPerformed

        tbpMain.addTab("Quản lý sinh viên", manageSV);

        tbpMain.setSelectedComponent(manageSV);
    }//GEN-LAST:event_mnuiQLActionPerformed

    private void mnuiKhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiKhaActionPerformed
        // TODO add your handling code here:
        if (hbKha == null) {
            hbKha = new HocBongKha();
            tbpMain.addTab("Học bổng loại Khá", hbKha);
        }
        tbpMain.setSelectedComponent(hbKha);
    }//GEN-LAST:event_mnuiKhaActionPerformed

    private void mnuiGioiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiGioiActionPerformed
        if (hbGioi == null) {
            hbGioi = new HocBongGioi();
            tbpMain.addTab("Học bổng loại Giỏi", hbGioi);
        }
        tbpMain.setSelectedComponent(hbGioi);
    }//GEN-LAST:event_mnuiGioiActionPerformed

    private void mnuiHocLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiHocLaiActionPerformed
        // TODO add your handling code here:
        if (dsHL == null) {
            dsHL = new DanhSachHocLai();
            tbpMain.addTab("Danh sach hoc lai", dsHL);
        }
        tbpMain.setSelectedComponent(dsHL);
    }//GEN-LAST:event_mnuiHocLaiActionPerformed

    private void mnuiMoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiMoFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Open a file");

        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.json", "json"));

        int value = fileChooser.showOpenDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            FileReader fr = null;
            try {
                fr = new FileReader(file);
                Gson gson = new Gson();

                java.lang.reflect.Type type = new TypeToken<List<SinhVien>>() {
                }.getType();

                data = gson.fromJson(fr, type);
                fillToJTable();
                tbpMain.addTab("Quản lý sinh viên", manageSV);
                tbpMain.setSelectedComponent(manageSV);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (fr != null) {
                    try {
                        fr.close();
                    } catch (IOException ex) {
                        Logger.getLogger(QuanLy.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_mnuiMoFileActionPerformed

    private void mnuiLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLuuFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save a file");

        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.json", "json"));

        int value = fileChooser.showSaveDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            FileWriter fw = null;
            try {
                fw = new FileWriter(file);

                Gson gson = new Gson();
                gson.toJson(data, fw);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (fw != null) {
                    try {
                        fw.flush();
                        fw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_mnuiLuuFileActionPerformed

    private void mnuiTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiTimKiemActionPerformed
        // TODO add your handling code here:
        if (timKiem == null) {
            timKiem = new TimKiemSinhVien();
            tbpMain.addTab("Tìm Kiếm Sinh Viên", timKiem);
        }
        tbpMain.setSelectedComponent(timKiem);
    }//GEN-LAST:event_mnuiTimKiemActionPerformed

    private void mnuiLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLocActionPerformed
        // TODO add your handling code here:
        if (loc == null) {
            loc = new locLopNienChe();
            tbpMain.addTab("Lọc theo lớp", loc);
        }
        tbpMain.setSelectedComponent(loc);
    }//GEN-LAST:event_mnuiLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                manHinh.setVisible(true);
            }
        });
    }

    public JTabbedPane getTbpMain() {
        return tbpMain;
    }

    public void setTbpMain(JTabbedPane tbpMain) {
        this.tbpMain = tbpMain;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuCongCu;
    private javax.swing.JMenu mnuQL;
    private javax.swing.JMenuItem mnuiGioi;
    private javax.swing.JMenuItem mnuiHocLai;
    private javax.swing.JMenuItem mnuiKha;
    private javax.swing.JMenuItem mnuiLoc;
    private javax.swing.JMenuItem mnuiLuuFile;
    private javax.swing.JMenuItem mnuiMoFile;
    private javax.swing.JMenuItem mnuiQL;
    private javax.swing.JMenuItem mnuiTimKiem;
    private javax.swing.JTabbedPane tbpMain;
    // End of variables declaration//GEN-END:variables
}
