/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlysinhviendemo.ui;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.mycompany.quanlysinhviendemo.model.CongNgheMang;
import com.mycompany.quanlysinhviendemo.model.KyNangMem;
import com.mycompany.quanlysinhviendemo.model.LapTrinhCanBan;
import com.mycompany.quanlysinhviendemo.model.MonHoc;
import com.mycompany.quanlysinhviendemo.model.SinhVien;
import com.mycompany.quanlysinhviendemo.model.SinhVienATTT;
import com.mycompany.quanlysinhviendemo.model.SinhVienCNTT;
import com.mycompany.quanlysinhviendemo.model.SinhVienDTVT;
import com.mycompany.quanlysinhviendemo.model.TheChat;
import com.mycompany.quanlysinhviendemo.model.TinHocDaiCuong;
import com.mycompany.quanlysinhviendemo.model.ToanCaoCapA1;
import com.mycompany.quanlysinhviendemo.model.ToanCaoCapA2;
import com.mycompany.quanlysinhviendemo.model.ToanCaoCapA3;
import com.mycompany.quanlysinhviendemo.model.TrietHoc;
import com.mycompany.quanlysinhviendemo.model.VatLyDaiCuong;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class QuanLy extends javax.swing.JPanel {

    public static List<SinhVien> data;
    DefaultTableModel model;
    public static int stt = 1;
    int selectedRowIndex;

    /**
     * Creates new form QuanLy
     */
    public QuanLy() {
        initComponents();
        cbxQuequan.setSelectedIndex(56);
        rbtnATTT.setSelected(true);
        data = new ArrayList<>();
        model = (DefaultTableModel) tblDanhSach.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngKhoa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtnATTT = new javax.swing.JRadioButton();
        rbtnCNTT = new javax.swing.JRadioButton();
        rbtnDTVT = new javax.swing.JRadioButton();
        txtMaSV = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jpDiem = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtKNM = new javax.swing.JTextField();
        txtLTCB = new javax.swing.JTextField();
        txtTC = new javax.swing.JTextField();
        txtTHDC = new javax.swing.JTextField();
        txtA1 = new javax.swing.JTextField();
        txtA2 = new javax.swing.JTextField();
        txtA3 = new javax.swing.JTextField();
        txtTH = new javax.swing.JTextField();
        txtVLDC = new javax.swing.JTextField();
        txtCNM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        cbxQuequan = new javax.swing.JComboBox<>();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnXoaSV = new javax.swing.JButton();

        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cổng thông tin sinh viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 450, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quê quán:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày sinh:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Khoa:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Lớp:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mã SV:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        rbtngKhoa.add(rbtnATTT);
        rbtnATTT.setText("ATTT");
        rbtnATTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnATTTActionPerformed(evt);
            }
        });
        add(rbtnATTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        rbtngKhoa.add(rbtnCNTT);
        rbtnCNTT.setText("CNTT");
        rbtnCNTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCNTTActionPerformed(evt);
            }
        });
        add(rbtnCNTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        rbtngKhoa.add(rbtnDTVT);
        rbtnDTVT.setText("DTVT");
        rbtnDTVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDTVTActionPerformed(evt);
            }
        });
        add(rbtnDTVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        add(txtMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, -1));

        txtNgaySinh.setToolTipText("");
        add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 210, -1));
        add(txtLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 210, -1));

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, -1));

        jpDiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Điểm");
        jpDiem.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Kỹ năng mềm");
        jpDiem.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Lập trình căn bản");
        jpDiem.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Thể chất");
        jpDiem.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Tin học đại cương");
        jpDiem.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Toán cao cấp A1");
        jpDiem.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Toán cao cấp A2");
        jpDiem.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Toán cao cấp A3");
        jpDiem.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Triết học");
        jpDiem.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Vật lý đại cương");
        jpDiem.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Công nghệ mạng");
        jpDiem.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtKNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKNMActionPerformed(evt);
            }
        });
        jpDiem.add(txtKNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, -1));
        jpDiem.add(txtLTCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, -1));
        jpDiem.add(txtTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, -1));
        jpDiem.add(txtTHDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, -1));
        jpDiem.add(txtA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, -1));
        jpDiem.add(txtA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, -1));
        jpDiem.add(txtA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 100, -1));
        jpDiem.add(txtTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, -1));
        jpDiem.add(txtVLDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, -1));
        jpDiem.add(txtCNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 100, -1));

        add(jpDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 340, 350));

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ và tên", "Mã SV", "Lóp", "Ngày sinh", "Quê quán", "Khoa", "Điểm TB"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMinWidth(45);
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(200);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(210);
            tblDanhSach.getColumnModel().getColumn(3).setMinWidth(55);
            tblDanhSach.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 770, 190));

        cbxQuequan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "BR_VT", "Bac Giang", "Bac Kan", "Bac Lieu", "Bac Ninh", "Ben Tre", "Binh Đinh", "Binh Duong", "Binh Phuoc", "Binh Thuan", "Ca Mau", "Can Tha", "Cao Bang ", "Da Nang", "Dak Lak", "Dak Nong", "Dien Bien", "Dong Nai", "Dong Thap", "Gia Lai", "Ha Giang", "Ha Nam", "Ha Noi ", "Ha Tinh", "Hai Duong", "Hai Phong", "Hau Giang", "Hoa Binh", "Hung Yen", "Khanh Hoa", "Kien Giang", "Kon Tum", "Lai Chau", "Lam Đong", "Lang Son", "Lao Cai", "Long An", "Nam Đinh", "Nghe An", "Ninh Bình", "Ninh Thuan", "Phu Tho", "Phu Yen", "Quang Binh", "Quang Nam", "Quang Ngai", "Quang Ninh", "Quang Tri", "Soc Trang", "Son La", "Tay Ninh", "Thai Binh", "Thai Nguyen", "Thanh Hoa", "Thua Thien Hue", "Tien Giang", "TP.Ho Chi Minh", "Tra Vinh", "Tuyen Quang", "Vinh Long", "Vinh Phuc", "Yen Bai" }));
        add(cbxQuequan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 210, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 462, -1, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 770, -1));

        btnXoaSV.setText("Xóa sinh viên");
        btnXoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSVActionPerformed(evt);
            }
        });
        add(btnXoaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnATTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnATTTActionPerformed
        rbtnATTT.setActionCommand(rbtnATTT.getText());
    }//GEN-LAST:event_rbtnATTTActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtKNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKNMActionPerformed


    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        txtHoTen.setText("");
        txtMaSV.setText("");
        txtCNM.setText("");
        txtNgaySinh.setText("");
        txtKNM.setText("");
        txtLTCB.setText("");
        txtLop.setText("");
        txtTC.setText("");
        txtTH.setText("");
        txtTHDC.setText("");
        txtVLDC.setText("");
        txtA1.setText("");
        txtA2.setText("");
        txtA3.setText("");
        cbxQuequan.setSelectedIndex(56);
        rbtngKhoa.setSelected(rbtnATTT.getModel(), true);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void rbtnCNTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCNTTActionPerformed
        rbtnCNTT.setActionCommand(rbtnCNTT.getText());
    }//GEN-LAST:event_rbtnCNTTActionPerformed

    private void rbtnDTVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDTVTActionPerformed
        rbtnDTVT.setActionCommand(rbtnDTVT.getText());
    }//GEN-LAST:event_rbtnDTVTActionPerformed

    private void fillToJTable() {
        if (data != null) {
            SinhVien sv = data.get(data.size() - 1);
            model.addRow(new Object[]{
                stt++,
                sv.getHoTen(),
                sv.getMaSV(),
                sv.getLopNienChe(),
                sv.getNgaySinh(),
                sv.getQueQuan(),
                sv.shortName,
                String.valueOf(sv.tinhDiem())
            });
        }
    }
    
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String hoTen = txtHoTen.getText();
        String maSV = txtMaSV.getText();
        String ngaySinh = txtNgaySinh.getText();
        String lop = txtLop.getText();
        double CNM = Double.parseDouble(txtCNM.getText());
        double KNM = Double.parseDouble(txtKNM.getText());
        double LTCB = Double.parseDouble(txtLTCB.getText());
        double TC = Double.parseDouble(txtTC.getText());
        double THDC = Double.parseDouble(txtTHDC.getText());
        double A1 = Double.parseDouble(txtA1.getText());
        double A2 = Double.parseDouble(txtA2.getText());
        double A3 = Double.parseDouble(txtA3.getText());
        double TH = Double.parseDouble(txtTH.getText());
        double VLDC = Double.parseDouble(txtVLDC.getText());
        MonHoc[] list = new MonHoc[10];
        list[0] = new CongNgheMang(CNM);
        list[1] = new KyNangMem(KNM);
        list[2] = new LapTrinhCanBan(LTCB);
        list[3] = new TheChat(TC);
        list[4] = new TinHocDaiCuong(THDC);
        list[5] = new ToanCaoCapA1(A1);
        list[6] = new ToanCaoCapA2(A2);
        list[7] = new ToanCaoCapA3(A3);
        list[8] = new TrietHoc(TH);
        list[9] = new VatLyDaiCuong(VLDC);
        rbtnATTT.setActionCommand(rbtnATTT.getText());
        rbtnCNTT.setActionCommand(rbtnCNTT.getText());
        rbtnDTVT.setActionCommand(rbtnDTVT.getText());

        String khoa = rbtngKhoa.getSelection().getActionCommand();
        String queQuan = cbxQuequan.getSelectedItem().toString();

        SinhVien sv;
        if (khoa.equals("ATTT")) {
            sv = new SinhVienATTT();
        } else if (khoa.equals("CNTT")) {
            sv = new SinhVienCNTT();
        } else {
            sv = new SinhVienDTVT();
        }
        sv.setHoTen(hoTen);
        sv.setMaSV(maSV);
        sv.setLopNienChe(lop);
        sv.setNgaySinh(ngaySinh);
        sv.setQueQuan(queQuan);
        sv.list[0].setDiem(CNM);
        sv.list[1].setDiem(KNM);
        sv.list[2].setDiem(LTCB);
        sv.list[3].setDiem(TC);
        sv.list[4].setDiem(THDC);
        sv.list[5].setDiem(A1);
        sv.list[6].setDiem(A2);
        sv.list[7].setDiem(A3);
        sv.list[8].setDiem(TH);
        sv.list[9].setDiem(VLDC);
        data.add(sv);
        fillToJTable();
        btnXoaActionPerformed(evt);
        //readJsonFile();
        //writeJsonFile();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        data.remove(selectedRowIndex);
        String hoTen = txtHoTen.getText();
        String maSV = txtMaSV.getText();
        String ngaySinh = txtNgaySinh.getText();
        String lop = txtLop.getText();
        double CNM = Double.parseDouble(txtCNM.getText());
        double KNM = Double.parseDouble(txtKNM.getText());
        double LTCB = Double.parseDouble(txtLTCB.getText());
        double TC = Double.parseDouble(txtTC.getText());
        double THDC = Double.parseDouble(txtTHDC.getText());
        double A1 = Double.parseDouble(txtA1.getText());
        double A2 = Double.parseDouble(txtA2.getText());
        double A3 = Double.parseDouble(txtA3.getText());
        double TH = Double.parseDouble(txtTH.getText());
        double VLDC = Double.parseDouble(txtVLDC.getText());
        MonHoc[] list = new MonHoc[10];
        list[0] = new CongNgheMang(CNM);
        list[1] = new KyNangMem(KNM);
        list[2] = new LapTrinhCanBan(LTCB);
        list[3] = new TheChat(TC);
        list[4] = new TinHocDaiCuong(THDC);
        list[5] = new ToanCaoCapA1(A1);
        list[6] = new ToanCaoCapA2(A2);
        list[7] = new ToanCaoCapA3(A3);
        list[8] = new TrietHoc(TH);
        list[9] = new VatLyDaiCuong(VLDC);
        rbtnATTT.setActionCommand(rbtnATTT.getText());
        rbtnCNTT.setActionCommand(rbtnCNTT.getText());
        rbtnDTVT.setActionCommand(rbtnDTVT.getText());

        String khoa = rbtngKhoa.getSelection().getActionCommand();
        String queQuan = cbxQuequan.getSelectedItem().toString();

        SinhVien sv;
        if (khoa.equals("ATTT")) {
            sv = new SinhVienATTT();
        } else if (khoa.equals("CNTT")) {
            sv = new SinhVienCNTT();
        } else {
            sv = new SinhVienDTVT();
        }
        sv.setHoTen(hoTen);
        sv.setMaSV(maSV);
        sv.setLopNienChe(lop);
        sv.setNgaySinh(ngaySinh);
        sv.setQueQuan(queQuan);
        sv.list[0].setDiem(CNM);
        sv.list[1].setDiem(KNM);
        sv.list[2].setDiem(LTCB);
        sv.list[3].setDiem(TC);
        sv.list[4].setDiem(THDC);
        sv.list[5].setDiem(A1);
        sv.list[6].setDiem(A2);
        sv.list[7].setDiem(A3);
        sv.list[8].setDiem(TH);
        sv.list[9].setDiem(VLDC);
        if (khoa.equals("ATTT")) {
            data.add(selectedRowIndex, sv);
            model.setValueAt(sv.getHoTen(), selectedRowIndex, 1);
            model.setValueAt(sv.getMaSV(), selectedRowIndex, 2);
            model.setValueAt(sv.getLopNienChe(), selectedRowIndex, 3);
            model.setValueAt(sv.getNgaySinh(), selectedRowIndex, 4);
            model.setValueAt(sv.getQueQuan(), selectedRowIndex, 5);
            model.setValueAt(sv.shortName, selectedRowIndex, 6);
            model.setValueAt(sv.tinhDiem(), selectedRowIndex, 7);
        } else if (khoa.equals("CNTT")) {
            data.add(selectedRowIndex, sv);
            model.setValueAt(sv.getHoTen(), selectedRowIndex, 1);
            model.setValueAt(sv.getMaSV(), selectedRowIndex, 2);
            model.setValueAt(sv.getLopNienChe(), selectedRowIndex, 3);
            model.setValueAt(sv.getNgaySinh(), selectedRowIndex, 4);
            model.setValueAt(sv.getQueQuan(), selectedRowIndex, 5);
            model.setValueAt(sv.shortName, selectedRowIndex, 6);
            model.setValueAt(sv.tinhDiem(), selectedRowIndex, 7);
        } else {
            //sv = new SinhVienDTVT(queQuan, maSV, hoTen, lop, date);
            data.add(selectedRowIndex, sv);
            model.setValueAt(sv.getHoTen(), selectedRowIndex, 1);
            model.setValueAt(sv.getMaSV(), selectedRowIndex, 2);
            model.setValueAt(sv.getLopNienChe(), selectedRowIndex, 3);
            model.setValueAt(sv.getNgaySinh(), selectedRowIndex, 4);
            model.setValueAt(sv.getQueQuan(), selectedRowIndex, 5);
            model.setValueAt(sv.shortName, selectedRowIndex, 6);
            model.setValueAt(sv.tinhDiem(), selectedRowIndex, 7);
        }

        btnXoaActionPerformed(evt);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        selectedRowIndex = tblDanhSach.getSelectedRow();
        SinhVien sv;
        if (model.getValueAt(selectedRowIndex, 6).toString().equals("ATTT")) {
            sv = new SinhVienATTT();
        } else if (model.getValueAt(selectedRowIndex, 6).toString().equals("CNTT")) {
            sv = new SinhVienCNTT();
        } else {
            sv = new SinhVienDTVT();
        }
        sv.setHoTen(model.getValueAt(selectedRowIndex, 1).toString());
        sv.setMaSV(model.getValueAt(selectedRowIndex, 2).toString());
        sv.setLopNienChe(model.getValueAt(selectedRowIndex, 3).toString());
        sv.setNgaySinh(model.getValueAt(selectedRowIndex, 4).toString());
        sv.setQueQuan(model.getValueAt(selectedRowIndex, 5).toString());
        sv.list[0].setDiem(data.get(selectedRowIndex).list[0].getDiem());
        sv.list[1].setDiem(data.get(selectedRowIndex).list[1].getDiem());
        sv.list[2].setDiem(data.get(selectedRowIndex).list[2].getDiem());
        sv.list[3].setDiem(data.get(selectedRowIndex).list[3].getDiem());
        sv.list[4].setDiem(data.get(selectedRowIndex).list[4].getDiem());
        sv.list[5].setDiem(data.get(selectedRowIndex).list[5].getDiem());
        sv.list[6].setDiem(data.get(selectedRowIndex).list[6].getDiem());
        sv.list[7].setDiem(data.get(selectedRowIndex).list[7].getDiem());
        sv.list[8].setDiem(data.get(selectedRowIndex).list[8].getDiem());
        sv.list[9].setDiem(data.get(selectedRowIndex).list[9].getDiem());

        txtHoTen.setText(sv.getHoTen());
        txtMaSV.setText(sv.getMaSV());
        txtLop.setText(sv.getLopNienChe());
        txtNgaySinh.setText(sv.getNgaySinh());
        cbxQuequan.setSelectedItem(sv.getQueQuan());
        if (model.getValueAt(selectedRowIndex, 6).toString().equals("ATTT")) {
            rbtngKhoa.setSelected(rbtnATTT.getModel(), true);
        } else if (model.getValueAt(selectedRowIndex, 6).toString().equals("CNTT")) {
            rbtngKhoa.setSelected(rbtnCNTT.getModel(), true);
        } else {
            rbtngKhoa.setSelected(rbtnDTVT.getModel(), true);
        }
        txtCNM.setText(String.valueOf(sv.list[0].getDiem()));
        txtKNM.setText(String.valueOf(sv.list[1].getDiem()));
        txtLTCB.setText(String.valueOf(sv.list[2].getDiem()));
        txtTC.setText(String.valueOf(sv.list[3].getDiem()));
        txtTHDC.setText(String.valueOf(sv.list[4].getDiem()));
        txtA1.setText(String.valueOf(sv.list[5].getDiem()));
        txtA2.setText(String.valueOf(sv.list[6].getDiem()));
        txtA3.setText(String.valueOf(sv.list[7].getDiem()));
        txtTH.setText(String.valueOf(sv.list[8].getDiem()));
        txtVLDC.setText(String.valueOf(sv.list[9].getDiem()));

        //data.remove(selectedRowIndex);
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnXoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSVActionPerformed
        // TODO add your handling code here:
        selectedRowIndex = tblDanhSach.getSelectedRow();
        if (selectedRowIndex != -1) {
            model.removeRow(selectedRowIndex);
            data.remove(selectedRowIndex);
            for (int i = selectedRowIndex; i < data.size(); i++) {
                model.setValueAt(Integer.parseInt(model.getValueAt(i, 0).toString()) - 1, i, 0);
            }
            stt--;
            btnXoaActionPerformed(evt);
        }
    }//GEN-LAST:event_btnXoaSVActionPerformed

    public JTable getTblDanhSach() {
        return tblDanhSach;
    }

    public void setTblDanhSach(JTable tblDanhSach) {
        this.tblDanhSach = tblDanhSach;
    }

    public JComboBox<String> getCbxQuequan() {
        return cbxQuequan;
    }

    public void setCbxQuequan(JComboBox<String> cbxQuequan) {
        this.cbxQuequan = cbxQuequan;
    }

    public JRadioButton getRbtnATTT() {
        return rbtnATTT;
    }

    public void setRbtnATTT(JRadioButton rbtnATTT) {
        this.rbtnATTT = rbtnATTT;
    }

    public JRadioButton getRbtnCNTT() {
        return rbtnCNTT;
    }

    public void setRbtnCNTT(JRadioButton rbtnCNTT) {
        this.rbtnCNTT = rbtnCNTT;
    }

    public JRadioButton getRbtnDTVT() {
        return rbtnDTVT;
    }

    public void setRbtnDTVT(JRadioButton rbtnDTVT) {
        this.rbtnDTVT = rbtnDTVT;
    }

    public ButtonGroup getRbtngKhoa() {
        return rbtngKhoa;
    }

    public void setRbtngKhoa(ButtonGroup rbtngKhoa) {
        this.rbtngKhoa = rbtngKhoa;
    }

    public JTextField getTxtA1() {
        return txtA1;
    }

    public void setTxtA1(JTextField txtA1) {
        this.txtA1 = txtA1;
    }

    public JTextField getTxtA2() {
        return txtA2;
    }

    public void setTxtA2(JTextField txtA2) {
        this.txtA2 = txtA2;
    }

    public JTextField getTxtA3() {
        return txtA3;
    }

    public void setTxtA3(JTextField txtA3) {
        this.txtA3 = txtA3;
    }

    public JTextField getTxtCNM() {
        return txtCNM;
    }

    public void setTxtCNM(JTextField txtCNM) {
        this.txtCNM = txtCNM;
    }

    public JTextField getTxtHoTen() {
        return txtHoTen;
    }

    public void setTxtHoTen(JTextField txtHoTen) {
        this.txtHoTen = txtHoTen;
    }

    public JTextField getTxtKNM() {
        return txtKNM;
    }

    public void setTxtKNM(JTextField txtKNM) {
        this.txtKNM = txtKNM;
    }

    public JTextField getTxtLTCB() {
        return txtLTCB;
    }

    public void setTxtLTCB(JTextField txtLTCB) {
        this.txtLTCB = txtLTCB;
    }

    public JTextField getTxtLop() {
        return txtLop;
    }

    public void setTxtLop(JTextField txtLop) {
        this.txtLop = txtLop;
    }

    public JTextField getTxtMaSV() {
        return txtMaSV;
    }

    public void setTxtMaSV(JTextField txtMaSV) {
        this.txtMaSV = txtMaSV;
    }

    public JTextField getTxtNgaySinh() {
        return txtNgaySinh;
    }

    public void setTxtNgaySinh(JTextField txtNgaySinh) {
        this.txtNgaySinh = txtNgaySinh;
    }

    public JTextField getTxtTC() {
        return txtTC;
    }

    public void setTxtTC(JTextField txtTC) {
        this.txtTC = txtTC;
    }

    public JTextField getTxtTH() {
        return txtTH;
    }

    public void setTxtTH(JTextField txtTH) {
        this.txtTH = txtTH;
    }

    public JTextField getTxtTHDC() {
        return txtTHDC;
    }

    public void setTxtTHDC(JTextField txtTHDC) {
        this.txtTHDC = txtTHDC;
    }

    public JTextField getTxtVLDC() {
        return txtVLDC;
    }

    public void setTxtVLDC(JTextField txtVLDC) {
        this.txtVLDC = txtVLDC;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaSV;
    private javax.swing.JComboBox<String> cbxQuequan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel jpDiem;
    private javax.swing.JRadioButton rbtnATTT;
    private javax.swing.JRadioButton rbtnCNTT;
    private javax.swing.JRadioButton rbtnDTVT;
    private javax.swing.ButtonGroup rbtngKhoa;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtA2;
    private javax.swing.JTextField txtA3;
    private javax.swing.JTextField txtCNM;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKNM;
    private javax.swing.JTextField txtLTCB;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTC;
    private javax.swing.JTextField txtTH;
    private javax.swing.JTextField txtTHDC;
    private javax.swing.JTextField txtVLDC;
    // End of variables declaration//GEN-END:variables
}
