/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlysinhviendemo.ui;

import com.mycompany.quanlysinhviendemo.model.SinhVien;
import static com.mycompany.quanlysinhviendemo.ui.Main.manageSV;
import static com.mycompany.quanlysinhviendemo.ui.QuanLy.data;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class TimKiemSinhVien extends javax.swing.JPanel {
    public static Main manHinh = new Main();


    /**
     * Creates new form TimKiemSinhVien
     */
    public TimKiemSinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(770, 580));
        setPreferredSize(new java.awt.Dimension(770, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Nhập Mã Sinh Viên Của Sinh Viên Cần Tìm Kiếm");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 47, -1, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 400, 40));

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if(txtTimKiem.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Ban Chua Nhap Ma Sinh Vien Can Tim", "Canh Bao:", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String key = txtTimKiem.getText();

        for (SinhVien s : data) {
            if (key.compareTo(s.getMaSV()) == 0) {
                if (s.shortName.equals("ATTT")) {
                    manageSV.getRbtngKhoa().setSelected(manageSV.getRbtnATTT().getModel(), true);
                } else if (s.shortName.equals("CNTT")) {
                    manageSV.getRbtngKhoa().setSelected(manageSV.getRbtnCNTT().getModel(), true);
                } else {
                    manageSV.getRbtngKhoa().setSelected(manageSV.getRbtnDTVT().getModel(), true);
                }
                manageSV.getCbxQuequan().setSelectedItem(s.getQueQuan());
                manageSV.getTxtHoTen().setText(s.getHoTen());
                manageSV.getTxtMaSV().setText(s.getMaSV());
                manageSV.getTxtNgaySinh().setText(s.getNgaySinh());
                manageSV.getTxtLop().setText(s.getLopNienChe());
                manageSV.getTxtCNM().setText(String.valueOf(s.list[0].getDiem()));
                manageSV.getTxtKNM().setText(String.valueOf(s.list[1].getDiem()));
                manageSV.getTxtLTCB().setText(String.valueOf(s.list[2].getDiem()));
                manageSV.getTxtTC().setText(String.valueOf(s.list[3].getDiem()));
                manageSV.getTxtTHDC().setText(String.valueOf(s.list[4].getDiem()));
                manageSV.getTxtA1().setText(String.valueOf(s.list[5].getDiem()));
                manageSV.getTxtA2().setText(String.valueOf(s.list[6].getDiem()));
                manageSV.getTxtA3().setText(String.valueOf(s.list[7].getDiem()));
                manageSV.getTxtTH().setText(String.valueOf(s.list[8].getDiem()));
                manageSV.getTxtVLDC().setText(String.valueOf(s.list[9].getDiem()));
                txtTimKiem.setText("");
                manHinh.getTbpMain().setSelectedComponent(manageSV);
                return;
            }   
        }
        txtTimKiem.setText("");
        JOptionPane.showMessageDialog(this, "Ma Sinh Vien Ban Nhap Chua Dung", "Canh Bao:", JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_btnTimKiemActionPerformed

    public JButton getBtnTimKiem() {
        return btnTimKiem;
    }

    public void setBtnTimKiem(JButton btnTimKiem) {
        this.btnTimKiem = btnTimKiem;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
